Working build for Windows, apparently

diff --git a/scripts/check_requirements_distribution b/scripts/check_requirements_distribution
--- a/scripts/check_requirements_distribution
+++ b/scripts/check_requirements_distribution
@@ -28,16 +28,20 @@ ls $SCRIPT_DIR/../deployer/bin/deployer || { $FAIL_CMD; FAILED=1; }
 echo -n "Checking for GitHub release access: "
 if [ "$OSTYPE" == "cygwin" ]; then
     node $(cygpath -am $SCRIPT_DIR/../deployer/index.js) -q -v || { $FAIL_CMD; FAILED=1; }
+    echo ""
 else
     node $SCRIPT_DIR/../deployer/index.js -q -v || { $FAIL_CMD; FAILED=1; }
+    echo ""
 fi
 echo -n "Checking for deploy host directory access: "
-set +o pipefail
-ssh $DEPLOY_HOST ls -d "$DEPLOY_PATH" || { $FAIL_CMD; FAILED=1; }
-set -o pipefail
-
-
+ssh "$DEPLOY_HOST" ls -d $(cygpath -u "$DEPLOY_PATH")
+if [ $? -gt 0 ]; then
+  FAILED=1;
+else
+  FAILED=0;
+fi
 
 if [ "$1" != "continue" ]; then
+  echo "Exit code $FAILED"
   exit $FAILED
 fi
